In [1]:
# one dim array
import numpy as np
arr = np.array([1,2,3,4,5])
type(arr)


numpy.ndarray

In [2]:
arr

array([1, 2, 3, 4, 5])

In [13]:
arr.shape

(5,)

In [17]:
arr.reshape(5,1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [19]:
arr.shape

(5,)

In [20]:
arr = np.array([[i for i in range(1,6)],[i for i in range(6,11)]])

In [21]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [22]:
arr.shape

(2, 5)

In [23]:
arr.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [24]:
arr.ndim

2

In [26]:
np.arange(1,5,2)

array([1, 3])

In [29]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [33]:
np.identity((2))

array([[1., 0.],
       [0., 1.]])

In [35]:
arr.dtype

dtype('int64')

In [37]:
# numpy vectorized operations
ar1 = np.array([i for i in range(1,6)])
ar2 = np.array([i for i in range(6,11)])
print(ar1-ar2)
print(ar1+ar2)
print(ar1/ar2)
print(ar1%ar2)

[-5 -5 -5 -5 -5]
[ 7  9 11 13 15]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
[1 2 3 4 5]


# universal operations

In [38]:
np.sqrt(ar1)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [41]:
np.sin(ar1)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [42]:
np.exp(ar1)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [43]:
np.log(ar1)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [63]:
# slicing
n = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
n

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [64]:
print(n[1,2:4])

[7 8]


In [65]:
n

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [70]:
n = n-1

In [71]:
n

array([[-1,  0,  1,  2],
       [ 3,  4,  5,  6],
       [ 7,  8,  9, 10]])

In [104]:
n[0,0] = 0

In [105]:
#normalization
arr = np.array([1,2,3,4,5])
mean = arr.mean()
std = arr.std()

In [106]:
normalized_data = (arr-mean)/std

In [107]:
normalized_data


array([-1.41421356, -0.70710678,  0.        ,  0.70710678,  1.41421356])

In [109]:
# logical operations
a = np.arange(10)
a[a >5]

array([6, 7, 8, 9])

In [1]:
import pandas as pd

In [15]:
ser = pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])

In [16]:
ser

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [17]:
data = {"a":1,
        "b":2,
        "c":3}

In [18]:
data

{'a': 1, 'b': 2, 'c': 3}

In [20]:
pd.Series(data)

a    1
b    2
c    3
dtype: int64